### ISSUE TITLE
Incident Closing?

### ISSUE THREAD

**Issue by Krylon360** [jangaraj/zabbix-script-servicenow#1]
Thanks for the alertscript for ServiceNow.
Any chance of adding functionality to auto-close the incident once the trigger has cleared?

Right now; we hacked together a PHP script that creates an entry in a "OMS_Events" table within our Zabbix DB which contains the Incident sysid and INC# and then issues a soap call to create on alert; and close on clear.

Would love to do away with this if possible; and use your script; but the auto-close function is crucial.

**Comment by jangaraj** [comment]
Yes, autoclosing feature is in my todo list. First unpublished draft for this feature already exists, but it'll be available only as "enterprise" version = paid version. Feel free to contact me, if you are interested.

**Comment by guruadminSN** [comment]
Hi Jangaraj,

Can you share the auto close script as well for reference.

Thanks
Guru
