### ISSUE TITLE
Incorrect usage of Create Service-Now incident from Zabbix script

### ISSUE THREAD

**Issue by boyemillar** [jangaraj/zabbix-script-servicenow#3]
When trying to send to servicenow i only receive the following returned into failure on zabbix.

Incorrect usage of Create Service-Now incident from Zabbix script
Example:
   zabbix-create-service-now-incident.py <to> <subject> <message>
   zabbix-create-service-now-incident.py "Jan Garaj" "PROBLEM" "
Trigger: Zabbix Server is down
Trigger description: Zabbix Server is down, please check it immediately
Trigger severity: Hight
Trigger nseverity: 4
Trigger status: Problem
Trigger URL:
Host: zabserver01
Host description: Main Zabbix Server
Event age: 10s
Current Zabbix time: 2015.06.19 21:23:12
Item values:
1. {ITEM.NAME1} ({HOST.NAME1}:{ITEM.KEY1}): {ITEM.VALUE1}
2. {ITEM.NAME2} ({HOST.NAME2}:{ITEM.KEY2}): {ITEM.VALUE2}
3. {ITEM.NAME3} ({HOST.NAME3}:{ITEM.KEY3}): {ITEM.VALUE3}
Zabbix event ID: 12345
Zabbix web UI: https://zabbix.domain.com/zabbix

When following this part of the configuration...

    At the Conditions tab, to only forward PROBLEM events:

   (A)	Maintenance status not in "maintenance" 
   (B)	Trigger value = "PROBLEM" 

I dont have an option to set option (B) in Zabbix v3.4.7 there is no "Trigger Value" option... could that be part of the problem.

**Comment by jangaraj** [comment]
No, you are not passing correct parameters to the script.

**Comment by boyemillar** [comment]
Are you able to elaborate further... I am unable to see where there is any difference other than in the condition above

**Comment by jangaraj** [comment]
README has been prepared for older (2.x) Zabbix version and you have 3.4. Please read https://www.zabbix.com/documentation/3.4/manual/config/notifications/media/script - I guess `Script parameters` will solve your problem.

**Comment by rahulkumartandf** [comment]
when running the python script  i am getting the error as below:

 python3 zabbix-create-service-now-incident.py
  File "zabbix-create-service-now-incident.py", line 46
    """
      ^

**Comment by jangaraj** [comment]
Please use python 2.

**Comment by rahulkumartandf** [comment]
Thnaks Pythn2 has reslolves this issue but still zabbix not creating
service now Incedent. could you know the reason ?

Thanks,
Rahul Kumar
Contact(M): 9958664330
