### ISSUE TITLE
zabbix snmp forwarding

### ISSUE THREAD

**Issue by priyankamondalairtel** [jangaraj/zabbix-script-servicenow#6]
Hi,

I am complete new here. I am trying to send snmptrap for alert forwarding from zabbix server.
the steps I followed:
1. Administration > Media Types and added a new mediatype send snmptrap
2. media added in user list
3. configuration > action and added new action and set operation.

configuration > action > operation
Trigger: {TRIGGER.NAME}
Trigger description: {TRIGGER.DESCRIPTION} 
Trigger severity: {TRIGGER.SEVERITY}
Trigger nseverity: {TRIGGER.NSEVERITY}
Trigger status: {TRIGGER.STATUS}
Trigger URL: {TRIGGER.URL}
Host: {HOST.HOST}
Host description: {HOST.DESCRIPTION}
Event age: {EVENT.AGE}
Current Zabbix time: {DATE} {TIME} 

Item values:

1. {ITEM.NAME1} ({HOST.NAME1}:{ITEM.KEY1}): {ITEM.VALUE1}
2. {ITEM.NAME2} ({HOST.NAME2}:{ITEM.KEY2}): {ITEM.VALUE2}
3. {ITEM.NAME3} ({HOST.NAME3}:{ITEM.KEY3}): {ITEM.VALUE3}

Zabbix event ID: {EVENT.ID}

and used custom script in mediatype:
vi /usr/lib/zabbix/alertscripts/zabbix-snmptrap:

snmptrap -v 1 -c public 10.5.100.155 '1.3.6.1.4.1.4000.1' '10.5.29.164' 6 99 '55' 1.3.6.1.4.1.4000.1.1  s "'{$(TRIGGER.NAME)}'" 1.3.6.1.4.1.4000.1.2  s "'${Trigger nseverity}'"

it is sending trp with no information:

generic_trap : "6"
iso.org.dod.internet.private.enterprises.4000.1.1 : "'{}'"
specific_trap : "99"
iso.org.dod.internet.private.enterprises.4000.1.2 : "{}"
enterprise : "iso.org.dod.internet.private.enterprises.4000.1"
int_ev_type : "SNMP"
peer_address : "10.5.29.164"
agent_address : "10.5.29.164"
timestamp : "55"

now the problem is how to get dynamic information in snmptrap
like: triggername, trigger description, hostname

any help would be appreciated

**Comment by jangaraj** [comment]
Sorry this is request for Zabbix support, which is not in the scope of this project.
